version: '3.8'
services:
  flybirds-system:
    container_name: young_flybirds_system
    restart: always
    network_mode: "bridge"
    labels:
      maintainers: "hax"
    build:
      context: /home/docker/flybirds/youngService/system
      dockerfile: dockerfile
    ports:
      - "9907:9907"
      - "8907:8907"
    environment:
      - TZ=Asia/Shanghai
    deploy:
      resources:
         limits:
            cpus: "0.50"
            memory: 1024M
         reservations:
            cpus: "0.25"
            memory: 128M
    volumes:
      - ./logs:/logs
