version: '3.8'
services:
  flybirds-gateway:
    container_name: young_flybirds_gateway
    restart: always
    network_mode: "bridge"
    labels:
      maintainers: "hax"
    build:
      context: /home/docker/flybirds/youngService/gateway
      dockerfile: dockerfile
    ports:
      - "9903:9903"
      - "8903:8903"
    environment:
      - TZ=Asia/Shanghai
    deploy:
      resources:
         limits:
            cpus: "0.50"
            memory: 512M
         reservations:
            cpus: "0.25"
            memory: 128M
    volumes:
      - ./logs:/logs
