version: '3.8'
services:
  seata-server:
    container_name: docker_seata_1.4.2
    image: seataio/seata-server:1.4.2
    hostname: seata-server
    restart: always
    ports:
      - "8091:8091"
    environment:
      - SEATA_PORT=8091
      - SEATA_IP=120.79.220.218
