version: '3'
services:
  minio:
    image: minio/minio
    hostname: "minio"
    ports:
      - 9000:9000 # api 端口
      - 9001:9001 # 控制台端口
    environment:
      MINIO_ACCESS_KEY: flybirds    #管理后台用户名
      MINIO_SECRET_KEY: flybirds@123 #管理后台密码，最小8个字符
      MINIO_SERVER_URL: http://119.91.25.140:9000
    volumes:
      - /home/flybirds/software/minio/data:/data               #映射当前目录下的data目录至容器内/data目录
      - /home/flybirds/software/minio/config:/root/.minio/     #映射配置目录
    command: server --console-address ':9001' /data  #指定容器中的目录 /data
    privileged: true
    restart: always
