spring:
  # 163邮箱服务
  mail:
    host: smtp.163.com
    port:
    username: 
    password: 
    protocol: smtp
    default-encoding: UTF-8
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
      mail.smtp.socketFactory.port: 465
      mail.smtp.socketFactory.class: javax.net.ssl.SSLSocketFactory
      mail.smtp.socketFactory.fallback: false

#web端配置
flybirds:
  platform:
    front:
      baseUrl: http://${flybirds.ip.host}:80/
      resetPwdUrl: http://${flybirds.ip.host}:80/forget/password?code={}&email={}
      updateEmailUrl: http://${flybirds.ip.host}:80/account/validate?type=updateEmail&code={}&email={}
# open-fengin hystrix 配置更改     
feign:
  hystrix:
    enabled: true
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
          strategy: SEMAPHORE
# 第三方登录
justauth:
  enabled: true
  type:
    GITEE: # Gitee中的redirect-uri必须配置，获取token的需要，否侧出现401无权限
      client-id: 
      client-secret: 
      ignore-check-redirect-uri: true
      redirect-uri: 
      scopes:
        - user_info
        - emails
  cache:
    type: REDIS
    prefix: 'social_auth_state:' # 缓存前缀，目前只对 Redis 缓存生效，默认 JUSTAUTH::STATE::
    timeout: 24h # 超时时长，目前只对 Redis 缓存生效，默认 3 分钟