version : '3.8'
services:
  nginx:
    container_name: docker_nginx
    image: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./html/dist:/home/flybirds/projects/flybirds-ui
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - ./logs:/var/log/nginx
      - ./conf/conf.d:/etc/nginx/conf.d
