FROM  openjdk:8-jre
# author
MAINTAINER flybirds
# 挂载目录
VOLUME /home/flybirds
# 创建目录
RUN mkdir -p /home/flybirds
# 指定路径
WORKDIR /home/flybirds
# 复制jar文件到路径
COPY ./jar/flybirds-oauth.jar /home/flybirds/flybirds-oauth.jar
#提示映射端口ls
EXPOSE 9906
EXPOSE 8906
# 启动网关服务
# ENTRYPOINT ["java","-jar","-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=8906","flybirds-oauth.jar"]
ENTRYPOINT ["java","-XX:+UnlockExperimentalVMOptions","-XX:+UseCGroupMemoryLimitForHeap","-jar","-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=8906","flybirds-oauth.jar"]
